import { PATHS } from "@/router/paths";

export const elementsArr = [
  { label: "Accordion", path: PATHS.COMPONENTS.ACCORDION },
  { label: "Alert", path: PATHS.COMPONENTS.ALERT },
  { label: "App Bar", path: PATHS.COMPONENTS.APP_BAR },
  { label: "Autocomplete", path: PATHS.COMPONENTS.AUTOCOMPLETE },
  { label: "Avatar", path: PATHS.COMPONENTS.AVATAR },
  { label: "Backdrop", path: PATHS.COMPONENTS.BACKDROP },
  { label: "Badge", path: PATHS.COMPONENTS.BADGE },
  { label: "Breadcrumb", path: PATHS.COMPONENTS.BREADCRUMB },
  { label: "Button", path: PATHS.COMPONENTS.BUTTON },
  { label: "Button Group", path: PATHS.COMPONENTS.BUTTON_GROUP },
  { label: "Button Navigation", path: PATHS.COMPONENTS.BUTTON_NAVIGATION },
  { label: "Card", path: PATHS.COMPONENTS.CARD },
  { label: "Checkbox", path: PATHS.COMPONENTS.CHECKBOX },
  { label: "Chip", path: PATHS.COMPONENTS.CHIP },
  { label: "Dialog", path: PATHS.COMPONENTS.DIALOG },
  { label: "Divider", path: PATHS.COMPONENTS.DIVIDER },
  { label: "Drawer", path: PATHS.COMPONENTS.DRAWER },
  { label: "Floating Action Button", path: PATHS.COMPONENTS.FLOATING_ACTION_BUTTON },
  { label: "Grid", path: PATHS.COMPONENTS.GRID },
  { label: "Image List", path: PATHS.COMPONENTS.IMAGE_LIST },
  { label: "List", path: PATHS.COMPONENTS.LIST },
  { label: "Menu", path: PATHS.COMPONENTS.MENU },
  { label: "Modal", path: PATHS.COMPONENTS.MODAL },
  { label: "Pagination", path: PATHS.COMPONENTS.PAGINATION },
  { label: "Paper", path: PATHS.COMPONENTS.PAPER },
  { label: "Popover", path: PATHS.COMPONENTS.POPOVER },
  { label: "Progress", path: PATHS.COMPONENTS.PROGRESS },
  { label: "Radio Group", path: PATHS.COMPONENTS.RADIO_GROUP },
  { label: "Rating", path: PATHS.COMPONENTS.RATING },
  { label: "Select", path: PATHS.COMPONENTS.SELECT },
  { label: "Skeleton", path: PATHS.COMPONENTS.SKELETON },
  { label: "Slider", path: PATHS.COMPONENTS.SLIDER },
  { label: "Speed Dial", path: PATHS.COMPONENTS.SPEED_DIAL },
  { label: "Stepper", path: PATHS.COMPONENTS.STEPPER },
  { label: "Switch", path: PATHS.COMPONENTS.SWITCH },
  { label: "Table", path: PATHS.COMPONENTS.TABLE },
  { label: "Tabs", path: PATHS.COMPONENTS.TABS },
  { label: "Text Field", path: PATHS.COMPONENTS.TEXT_FIELD },
  { label: "Textarea", path: PATHS.COMPONENTS.TEXTAREA },
  { label: "Toggle Button", path: PATHS.COMPONENTS.TOGGLE_BUTTON },
  { label: "Tooltip", path: PATHS.COMPONENTS.TOOLTIP },
  { label: "Transfer List", path: PATHS.COMPONENTS.TRANSFER_LIST },
  { label: "Typography", path: PATHS.COMPONENTS.TYPOGRAPHY },
].sort((a, b) => a.label.localeCompare(b.label));