export const teamMembers = [
  {
    name: 'Sarah Chen',
    role: 'CEO & Founder',
    image: '/images/avatar.png',
    initials: 'SC',
    bio: 'Passionate about building products that make a difference. 10+ years in tech leadership.',
    email: 'sarah@company.com',
    linkedin: '#',
  },
  {
    name: 'Alex Johnson',
    role: 'Head of Operations',
    image: '/images/avatar-2.png',
    initials: 'AJ',
    bio: 'Operations leader focused on scaling processes and building efficient systems.',
    email: 'alex@company.com',
    linkedin: '#',
  },
  {
    name: 'Emily Watson',
    role: 'Head of Design',
    image: '/images/avatar.png',
    initials: 'EW',
    bio: 'Creative director focused on user-centered design and brand experiences.',
    email: 'emily@company.com',
    linkedin: '#',
  },
  {
    name: 'David Kim',
    role: 'Head of Product',
    image: '/images/avatar-2.png',
    initials: 'DK',
    bio: 'Product strategist with a track record of launching successful digital products.',
    email: 'david@company.com',
    linkedin: '#',
  },
  {
    name: 'Lisa Thompson',
    role: 'Head of Marketing',
    image: '/images/avatar.png',
    initials: 'LT',
    bio: 'Growth marketing expert specializing in digital campaigns and brand building.',
    email: 'lisa@company.com',
    linkedin: '#',
  },
  {
    name: 'Marcus Rodriguez',
    role: 'Head of Engineering',
    image: '/images/avatar-2.png',
    initials: 'MR',
    bio: 'Full-stack engineer with expertise in scalable systems and team leadership.',
    email: 'marcus@company.com',
    linkedin: '#',
  },
]; 