export const PATHS = {
  ELEMENTS: {
    OVERVIEW: "/elements",
    ACCORDION: "/elements/accordion",
    ALERT: "/elements/alert",
    APP_BAR: "/elements/app-bar",
    AVATAR: "/elements/avatar",
    BREADCRUMB: "/elements/breadcrumb",
    BUTTON: "/elements/button",
    CARD: "/elements/card",
    CAROUSEL: "/elements/carousel",
    DIALOG: "/elements/dialog",
    DRAWER: "/elements/drawer",
    DND: "/elements/dnd",
    EDITOR: "/elements/editor", 
    PAGINATION: "/elements/pagination",
    POPOVER: "/elements/popover",
    STEPPER: "/elements/stepper",
    TABLE: "/elements/table",
    TIMELINE: "/elements/timeline",
    OTP: "/elements/otp",
  },
  DOCS: {
    ROOT: "/docs",
    INTRO: "/docs/intro",
    INSTALL: "/docs/installation",
  },
  BLOCKS: {
    OVERVIEW: "/blocks",
    ABOUT: "/blocks/about",
    CALL_TO_ACTION: "/blocks/call-to-action",
    CONTACT: "/blocks/contact",
    COPYRIGHT: "/blocks/copyright",
    FAQ: "/blocks/faq",
    FEATURE_PRODUCT: "/blocks/feature-device",
    FEATURE_BENEFIT: "/blocks/feature-benefit",
    FOOTER: "/blocks/footer",
    HERO: "/blocks/hero",
    NEWSLETTER_SUBSCRIPTION: "/blocks/newsletter-subscription",
    PRICING_MENU: "/blocks/pricing-menu",
    PRICING_TABLE: "/blocks/pricing-table",
    SERVICES: "/blocks/services",
    SINGLE_PROFILE: "/blocks/single-profile",
    TEAM: "/blocks/team",
    TESTIMONIAL_GRID: "/blocks/testimonial-grid",
    TESTIMONIAL_SLIDER: "/blocks/testimonial-slider",
    COMING_SOON: "/blocks/coming-soon",
  },
  TEMPLATES: {
    ROOT: "/templates",
  },
  DASHBOARD: {
    ROOT: "/dashboard",
  },
  FORM: {
    ROOT: "/form",
  },
  ABOUT: "/about",

  FOOTER: {
    REPORT_BUG: "/report-bug",
    CHANGE_LOG: "/change-log",
    CONTACT: "/contact",
  },
};
